---
- name: Update hostname
  ansible.builtin.hostname:
    name: "T-YAROSLAVOVYCH-lab2"

- name: Ensure /etc/hostname has the correct value
  ansible.builtin.copy:
    content: "T-YAROSLAVOVYCH-lab2\n"
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'

- name: Reboot to apply hostname change
  ansible.builtin.reboot:
    msg: "Rebooting to apply new hostname"
    reboot_timeout: 60
