#---
#- name: Update hostname on remote server
 # hosts: my_servers
  #become: yes
  #roles:
   # - dummy_role

#- name: Reboot hostname
 # become: true
  #ansible.builtin.command: hostnamectl set-hostname T-YAROSLAVOVYCH-lab2

#---
#- name: Update hostname on remote server
#  hosts: my_servers
#  become: true
#
 # tasks:
  #  - name: Reboot hostname
   #   ansible.builtin.command:
    #    cmd: hostnamectl set-hostname T-YAROSLAVOVYCH-lab2

---
- name: Update hostname on remote server
  hosts: my_servers
  become: true

  tasks:
    - name: Set hostname using hostnamectl
      ansible.builtin.command:
        cmd: hostnamectl set-hostname "{{ ansible_hostname | regex_replace('^.*$', 'name-surename-lab2') }}"

    - name: Update /etc/hostname file
      ansible.builtin.copy:
        content: "{{ ansible_hostname | regex_replace('^.*$', 'name-surename-lab2') }}"
        dest: /etc/hostname
        owner: root
        group: root
        mode: '0644'

    - name: Reboot to apply changes
      ansible.builtin.reboot:
        reboot_timeout: 600
